version: '3'
services:
  nextjs-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # client port

  nestjs-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # server port
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: live-chat-user
      POSTGRES_PASSWORD: live-chat-password
      POSTGRES_DB: live-chat

  redis:
    image: redis:7.2.1
