version: '3'
services:
  nextjs-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # client port

  nestjs-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # server port
    depends_on:
      - postgres
      - redis

  # PostgreSQL veritabanı
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name

  # Redis
  redis:
    image: redis:latest
