version: '3'
services:
  nextjs-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
    ports:
      - '3000:3000' # client port
    networks:
      - video-chat

  nestjs-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '8080:8080' # server port
    depends_on:
      - postgres
      - redis
    networks:
      - video-chat

  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    networks:
      - video-chat
    environment:
      POSTGRES_USER: live-chat-user
      POSTGRES_PASSWORD: live-chat-password
      POSTGRES_DB: live-chat

  redis:
    image: redis:7.2.1
    ports:
      - '6379:6379'
    networks:
      - video-chat
networks:
  video-chat:
    driver: bridge
