import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import React from 'react'

const poppins = Poppins({ subsets: [ 'latin' ], weight: [ '400', '500', '600', '700' ] })

export const metadata : Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export type RootLayoutTypes = {
  children : React.ReactNode
}

export default function RootLayout({ children } : RootLayoutTypes) {
  return (
    <html lang="en">
    <body className={poppins.className}>
    {children}
    </body>
    </html>
  )
}
